In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
array.shape

(4, 3)

In [4]:
array.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
array.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [6]:
array.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
array[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array[3:]

array([[10, 11, 12]])

In [11]:
array[:, 1]

array([ 2,  5,  8, 11])

In [12]:
array[:, :]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
array[1, :]

array([4, 5, 6])

In [14]:
array[1]

array([4, 5, 6])

In [15]:
array > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
array[array > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
X = np.arange(20).reshape(-1, 1)

In [18]:
X

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [19]:
np.random.seed(0)
y = np.random.rand(20)

In [20]:
y

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [21]:
y = np.where(y < 0.5, 0, 1).reshape(-1, 1)

In [22]:
y

array([[1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [23]:
X[y == 1]

array([ 0,  1,  2,  3,  5,  7,  8, 10, 11, 12, 13, 17, 18, 19])

In [24]:
X[y >= 0.5]

array([ 0,  1,  2,  3,  5,  7,  8, 10, 11, 12, 13, 17, 18, 19])

In [25]:
array_1 = np.array([[1, 2], 
                    [3, 4], 
                    [5, 6]])
array_2 = np.array([[7, 8], 
                    [9, 10], 
                    [11, 12]])

In [26]:
np.vstack([array_1, array_2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [27]:
np.hstack([array_1, array_2])

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [28]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.zeros([4, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros_like(array)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
np.ones_like(array)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
np.random.seed(0)

In [35]:
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [36]:
np.random.randn(10)

array([ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
        0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [37]:
np.random.randint(0, 100, 10)

array([ 9, 57, 32, 31, 74, 23, 35, 75, 55, 28])

In [38]:
array_1 + array_2

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [39]:
array_1 - array_2

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [40]:
array_1 * array_2

array([[ 7, 16],
       [27, 40],
       [55, 72]])

In [41]:
array_1 / array_2

array([[0.14285714, 0.25      ],
       [0.33333333, 0.4       ],
       [0.45454545, 0.5       ]])

In [42]:
array ** 2

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]], dtype=int32)

In [43]:
np.sqrt(array)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [44]:
np.exp(array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [45]:
np.log1p(array)

array([[0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936]])

In [46]:
array_3 = np.random.randint(0, 100, 20)
array_3

array([34,  0,  0, 36, 53,  5, 38, 17, 79,  4, 42, 58, 31,  1, 65, 41, 57,
       35, 11, 46])

In [47]:
np.sum(array_3)

653

In [48]:
np.mean(array_3)

32.65

In [49]:
np.var(array_3)

533.1274999999999

In [50]:
np.std(array_3)

23.0895539151366

In [51]:
np.max(array_3)

79

In [52]:
np.argmax(array_3)

8

In [53]:
array_3[np.argmax(array_3)]

79

In [54]:
array.dtype

dtype('int32')

In [55]:
array_4 = np.random.randn(10)
array_4

array([ 1.29269823, -0.73145824, -1.60540226,  0.98947618,  0.11081461,
       -0.38093141,  0.11495917,  0.34531264, -1.73495876,  1.65835111])

In [56]:
np.round(array_4, 3)

array([ 1.293, -0.731, -1.605,  0.989,  0.111, -0.381,  0.115,  0.345,
       -1.735,  1.658])